version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2020-03-19T21-49-00Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: server /data
